import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "../context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppProvider>
        <body className="mx-4 my-8 space-y-8 bg-gray-100">
          {children}
          <div id="portal" className="fixed"></div>

        </body>
      </AppProvider>
    </html>
  );
}
